npmRegistries:
  "https://compstak-prod-278696104475.d.codeartifact.us-east-1.amazonaws.com/npm/frontend/":
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"

npmScopes:
  compstak:
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
    npmRegistryServer: "https://compstak-prod-278696104475.d.codeartifact.us-east-1.amazonaws.com/npm/frontend/"

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
